# Generated by Django 3.2.6 on 2021-09-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccidentWebAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='uname',
        ),
    ]
